name: Ontvangst goederen
on:
  schedule:
  - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  ontvangst-goederen:
    runs-on: ubuntu-latest
    steps:
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "content/testfile.md"
          FILE_DATA: "file content"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
